version: "3.8"

services:
  page:
    container_name: page
    depends_on:
      - db
    build:
      context: ./page
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: ${SERVICE_NAME_PAGE}
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - page:/home/transcendance/${SERVICE_NAME_PAGE}
    tty: true
    networks:
      - pong
    init: true
    restart: on-failure

  online:
    container_name: online
    depends_on:
      - db
    build:
      context: ./online
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: ${SERVICE_NAME_ONLINE}
    env_file:
      - .env
    expose:
      - "8001"
    volumes:
      - online:/home/transcendance/${SERVICE_NAME_ONLINE}
    tty: true
    networks:
      - pong
    init: true
    restart: on-failure

  bot:
    container_name: bot
    depends_on:
      - db
    build:
      context: ./bot
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: ${SERVICE_NAME_BOT}
    env_file:
      - .env
    expose:
      - "8002"
    volumes:
      - bot:/home/transcendance/${SERVICE_NAME_BOT}
    tty: true
    networks:
      - pong
    init: true
    restart: on-failure


  db:
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - pong
    restart: on-failure

  nginx:
    container_name: nginx
    depends_on:
      - online
      - page
      - bot
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - nginx:/etc/nginx
    networks:
      - pong
    env_file: .env
    # tty: true
    restart: on-failure

volumes:
  online:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/joerober/Desktop/git/volume_online'
  postgres:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/joerober/Desktop/git/volume_db'
  nginx:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/joerober/Desktop/git/volume_nginx'
  page:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: '/Users/joerober/Desktop/git/volume_page'
  bot:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: '/Users/joerober/Desktop/git/volume_bot'

networks:
  pong:
    driver: bridge