version: "3.8"

services:
  django2:
    container_name: django2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: ${SERVICE_NAME}
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - django2:/home/transcendance/${SERVICE_NAME}
    tty: true
    # networks:
    #   - pong
    init: true

  db:
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  

volumes:
  django2:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/joerober/code/tests/ping/git/volume'
  postgres:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/joerober/code/tests/ping/git/volume_db'

# networks:
#   pong:
#     driver: bridge