# Generated by Django 4.2.11 on 2024-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='left',
        ),
        migrations.RemoveField(
            model_name='room',
            name='right',
        ),
        migrations.AddField(
            model_name='room',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
