# Generated by Django 4.2.11 on 2024-05-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_room_left_remove_room_right_room_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quickmatch',
            field=models.BooleanField(default=False),
        ),
    ]
