version: "3.8"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - django:/home/transcendance
    tty: true
    # networks:
    #   - pong
    init: true

  db:
    image: postgres:16.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  

volumes:
  django:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/joerober/code/tests/ping/git/docker/django/volume'
  postgres:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/joerober/code/tests/ping/git/docker/django/volume_db'

# networks:
#   pong:
#     driver: bridge